### ISSUE TITLE
can I attach my own decorator to this?

### ISSUE THREAD

**Issue by bbottema** [better-js-logging/angular-logger#10]
_From @edamon on January 15, 2016 22:41_

This is a pretty nice library, thanks!  I want to know if I can use a decorator to intercept the $log methods, because I want to allow for logging to an external source, like stacktracejs or trackjs.  Theoretically it should work, but it doesn't seem to be.

Edit:
I've figured out how to decorate the global $log.debug, $log.error, etc methods, but not sure how I can do it for specific $log.getInstance('string') objects.

_Copied from original issue: pdorgambide/angular-logger#24_

**Comment by bbottema** [comment]
_From @fdnhkj on January 16, 2016 20:40_

 :+1:  
I was also looking for this, I would like to intercept the log messages.
I also tried to implement it by decorating $log (after angular-logger's decorator).
And indeed, it is possible for $log.info, $log.error, ... functions.

But it looks like it is not possible to decorate `getInstance` function.
I see in the code that `getInstance` function is defined in the run phase of the `angular-logger` module.
That's probably why we cannot decorate this function (as, AFAIK, decorator feature is only available in config phase).

**Comment by bbottema** [comment]
_From @edamon on January 18, 2016 23:10_

Since the $log object is preserved in the `.$$orig$log` property, it is possible to still intercept the $log messages, but you can't do anything with the context provided to `GetInstance(context)` (like check it's logLevel), because it hasn't been created yet, and there's no way to get to it.

``` javascript
    $provide.decorator( '$log', [ '$delegate', function( $delegate )
    {
      // Save the original $log.debug()
      var nativeLog = $delegate.$$orig$log; //this is the original $log that logEnhancer replaced.
      var debugFn = $delegate.debug; //this is the logEnhancers drop in replacement for $log.  angular-logger config module ran first, so it has already put a decorator on $log

      function sendLogs( )
      {
        var levels = $delegate.LEVEL;    //this is the LEVELS object.
        var curLevel = $delegate.logLevels['*'];  //this is the levels set in the logEnhancerProvider

        var args    = [].slice.call(arguments);

        //you can do this for $log.debug, but not for $log.getInstance('foo').debug, because there's no way to get to the context
        //if (curLevel <= levels.DEBUG) {
          //send the log to some external persistance
          console.log(moment().toString() + ': do intercepty stuff: ', args);

          // Call the original with the output prepended with formatted timestamp
          debugFn.apply(null, args);
        //}
      };

      nativeLog.debug = sendLogs;
      $delegate.debug = sendLogs;
      return $delegate;
    }]);

    logEnhancerProvider.logLevel = { '*': logEnhancerProvider.LEVEL.TRACE };
```

**Comment by bbottema** [comment]
I will look into this somewhere this week.

**Comment by bbottema** [comment]
@edamon, @fdnhkj

I did a quickfix in [v1.0.5](https://github.com/better-js-logging/angular-logger/releases/tag/1.0.5), with which you can now access the `getInstance` function:

``` javascript
this.instanceFactoryFactory = function($log) {
    return function(context) {
        return {
            trace   : logEnhancer.enhanceLogging($log.$$orig$log.debug, $log.LEVEL.TRACE, context, $log, provider.datetimePattern, provider.datetimeLocale, provider.prefixPattern),
            debug   : logEnhancer.enhanceLogging($log.$$orig$log.debug, $log.LEVEL.DEBUG, context, $log, provider.datetimePattern, provider.datetimeLocale, provider.prefixPattern),
            log     : logEnhancer.enhanceLogging($log.$$orig$log.log,   $log.LEVEL.INFO,  context, $log, provider.datetimePattern, provider.datetimeLocale, provider.prefixPattern),
            info    : logEnhancer.enhanceLogging($log.$$orig$log.info,  $log.LEVEL.INFO,  context, $log, provider.datetimePattern, provider.datetimeLocale, provider.prefixPattern),
            warn    : logEnhancer.enhanceLogging($log.$$orig$log.warn,  $log.LEVEL.WARN,  context, $log, provider.datetimePattern, provider.datetimeLocale, provider.prefixPattern),
            error   : logEnhancer.enhanceLogging($log.$$orig$log.error, $log.LEVEL.ERROR, context, $log, provider.datetimePattern, provider.datetimeLocale, provider.prefixPattern)
        };
    };
}
```

You can replace `instanceFactoryFactory` with your own fancy version :)

**Comment by edamon** [comment]
Thanks for the quick turnaround!  I have an idea for this.  If you attach a dictionary of "appenders" to $log during config, then that provides a hook for people to add those functions during their config using the enhanceLogggingProvider.  Then, in the enhance logging function, you could filter those by log level and call them where you call `loggingFunc.apply(null, enhancedArguments);`  The appenders could be a collection of  objects something like `{ loglevel, appenderFunction() }`, or even add a target like `moda.subB`.

This way we don't have to write decorators for $log to try and persist logs, we can just add those methods using the provider, and they should get called for global and instance loggers. 

What do you think?  I was thinking about forking and attempting that.

**Comment by bbottema** [comment]
Go ahead!

**Comment by ap1969** [comment]
Hi,
Sorry, can i ask for some help on this? Is there any chance you could demonstrate how to override the instanceFactory (with just a dummy function), please? I'd like to use this module both on my mobile app and companion web app, but route the mobile logs to Loggly. I've tried to get this working, but I struggle with angular providers, etc. Any help would be greatly appreciated!

Regards,
Andy
