### ISSUE TITLE
Integration with Webpack Difficult

### ISSUE THREAD

**Issue by SunburnedGoose** [better-js-logging/angular-logger#14]
It wasn't easy to get this to work with webpack because it is wrapped in a IIFE and it made it difficult for it to find the export from the angular.module function.  

I was able to get it to work in the end just importing the script into Webpack but it's isn't as clean as I'd like it to be.  

I am in the same boat as you with users asking for ES6/CommonJS exports.  You could use Babel/SystemJS/RollUp to produce a library file that works with these bundlers.

Thanks for you work, it's been helpful.  

btw, I'm using this in http://github.com/DestinyItemManager

**Comment by bbottema** [comment]
I'm also just loading the module after angular and it registers itself as a provider. What is it specifically that you wanted to expose as exported module?

**Comment by SunburnedGoose** [comment]
Because of the IIFE, Webpack can't grab the export, so it doesn't let me use the syntax, 

```
require("angular-logger");
```

For that to work, your code would have to drop the IIFE and be based on this, 

```
export default angular.module('logger', [])...
```

Since webpack can't see angular-logger, it doesn't load it's dependencies sprintf or moment.  I have to do all of this manually.

https://github.com/DestinyItemManager/dim-mobile-client/blob/master/src/app/dimApp.module.js#L3-L5

In an ideal world, it's just

```
import angularLogger form 'angular-logger' // Webpack finds the export from the package.json entry & its dependencies
angular.module('dimApp', [angularLogger.name]); // module.name property
```

**Comment by bbottema** [comment]
That's strange, because require("angular-logger"); is exactly what I do. Are you using typescript or es6? 

It doesn't actually need to export anything, because angular-logger exposes itself directly in angular by registering a provider. Granted angular-logger currently expects angular to be available globally (that can be improved).

**Comment by bbottema** [comment]
It doesn't need to export anything, because angular-logger exposes itself directly in angular by registering a provider. Granted angular-logger currently expects angular to be available globally.

**Comment by bbottema** [comment]
Sorry for the terse messages, I'm on my phone currently

**Comment by SunburnedGoose** [comment]
Yes, if I just include your script into the page after angular is loaded, it will register itself..  but the thing about webpack is it bundles all the scripts into one file, and it loads them asynchronously.  Webpack handles this by understanding a dependency graph, but it can't read your files because of the IIFE and no global export.  So I had to shim angular-logger into webpack where I referenced my repo earlier.  

Because of the shim, I can't bundle your code into a vendor bundle, and instead it gets bundled into mine.

https://github.com/DestinyItemManager/dim-mobile-client/blob/master/webpack.config.js#L16-L27

You would probably have the same issue if you're trying to use SystemJS or RollUp bundles too.  

After webpack bundles, it updates my index.html file with the bundled files:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title>Destiny Item Manager v4</title>
    <style>
[ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
  display: none !important;
}
    </style>
  </head>
  <body>
    <ion-nav-view class="ng-cloak"></ion-nav-view>
    <script src="js/vendors.js"></script>
    <script src="js/polyfill.js"></script>
    <script src="cordova.js"></script>
    <script src="js/bundle.js"></script>
    <!-- dim-mobile-client v0.0.1 built on Wed Feb 17 2016 02:14:48 GMT-0600 (CST) -->
  </body>
</html>

```

**Comment by bbottema** [comment]
One problem is I don't know how to do optional requires. If you leave out sprintf and momentjs, but have require statements, the compiler will report an error. Any clues how to deal with that in commonjs?

**Comment by SunburnedGoose** [comment]
I'll fork it and try my hand.

**Comment by bbottema** [comment]
It is greatly appreciated. 

I started migrating one of my projects from Grunt to WebPack only a week ago so I'm learning a lot of things every day.

**Comment by bbottema** [comment]
I'm starting to think I should just provide two versions, one fixed with dependencies and one without (_angular-logger_ and _angular-logger-lite_). Then I can stop relying on globals on `window` and just export it normally with requires and strip the IIFE.

@SunburnedGoose, did you start yet? Else I will start moving on this. These optional dependencies have been an annoyance for longer now and I just want to streamline everything.

**Comment by SunburnedGoose** [comment]
I didn't start it yet.

**Comment by SunburnedGoose** [comment]
You should be able to add a jsnext:main to your project.json file to point to the new files.

**Comment by bbottema** [comment]
@SunburnedGoose, so sadly, I didn't get around to doing it after all, but I really want to support webpack and other module systems properly.

I would still prefer to work with optional dependencies for momentjs and sprintf rather than splitting up into two separate projects.

Do you know of a solution?

**Comment by SunburnedGoose** [comment]
afaik, you don't include them into your package.json file and leave that as a note in the readme for the implementor to include it if they want it.  There is no optional flag for dependencies.

**Comment by bbottema** [comment]
Yeah so that won't work, because you they're loaded through a module system, they won't be available on the global window. And I can't require them as modules, because they become explicit dependencies in that case and it will fail either during bundling or in runtime.

**Comment by SunburnedGoose** [comment]
With webpack, you can assign modules to the global variable for backwards compatibility.  It's how I got it to work.

**Comment by bbottema** [comment]
Yeah I figured as much. Not the neatest way of allowing optional dependencies, but it will work.

**Comment by bbottema** [comment]
@SunburnedGoose I'm not getting enough time in to fix this right now, but here's a way to keep it out of your own sources, using an external.ts approach (the example is with Prism.js, but it should work with any other library distribution):

https://github.com/tpadjen/ng2-prism/issues/6#issuecomment-228854007

**Comment by bbottema** [comment]
@SunburnedGoose angular-logger 1.3.2 should fix it.
