### ISSUE TITLE
bower wiredep integration

### ISSUE THREAD

**Issue by badia-kharroubi** [better-js-logging/angular-logger#16]
wiredep dont inject angular-logger.js in index.html.
This is because of missing bower.json file.
It is important to have main to dist files.
We exclude all files but dist, LICENSE and README.md
It can be :

``` javascript
{
  "name": "angular-logger",
  "main": "dist/angular-logger.js",
  "version": "1.3.1",
  "homepage": "https://github.com/better-js-logging/angular-logger",
  "authors": [
    "Benny Bottema <b.bottema@projectnibble.org>",
    "Pablo Dorgambide <pdorgambide@qualigy.com>"
  ],
  "description": "> Enhance $log for better logging, including patterns and level management",
  "license": "MIT",
  "keywords": [
    "angular",
    "logger",
    "logging",
    "angular-logger",
    "$log"
  ]
  "ignore": [
    "bower_components",
    "node_modules",
    "src",
    "spec",
    ".codeclimate.yml",
    ".coveralls.yml",
    ".gitignore",
    ".jshintrc",
    ".travis.yml",
    "enhanced-logging.png",
    "gulpfile.js",
    "package.json",
  ]
}
```

We can make it work without bower.json file but it is not a clean solution: 
Update your angular project to use wiredep >= 3.0.0
Override your angular project bower.json with:

``` javascript
"dependencies": {
    "angular": "1.4.9",
    ...
    "moment": "2.10.6",
    "sprintf": "1.0.3",
    "angular-logger": "~1.3.1"

  },
  "overrides": {
    "angular-logger": {
      "main": "dist/angular-logger.js",
      "dependencies": {
        "angular": "1.x.x",
        "moment": "*",
        "sprintf": "*"
      }
    }
  },
  "devDependencies": {
    ...
  }
```

**Comment by bbottema** [comment]
@badia-kharroubi, I re-added a bower.json file, but actually, it was missing because angular-logger migrated to npm for managing dependencies. However, I can still provide an entry point for bower, for those who still use it.

In case you are interested in moving to NPM [as well](https://github.com/better-js-logging/angular-logger/commit/cca4b5d3649b6db9f71864cb7080cdceb26eaa22#commitcomment-16334383):

> You can do that in two ways (I just went through this learning phase myself):
> 
> For both approaches, copy the entire dependency list over from bower.json to package.json. The versions might not match exactly, so a npm list can give you the latest versions of each. After correcting the versions do an npm install which brings in all the modules in node_modules, similar to bower_modules.
> 
> Now I'm not aware of a NPM aware wiredep. That's because with NPM you do this a little different. Which brings me to the two approaches I mentioned earlier:
> 
> approach one: manually insert script dependencies in your HTML that point to the dist versions of each dependency in the node_modules folder (or where ever you copy it if you copy). No wiredep I'm aware of that can help you here
> approach two: this is the modern approach these days: use an import system (I recommend commonjs, which works the same as require statements in nodejs if you use browserify or webpack). Then simply require() the modules you need and the packer/bundler/buildtool whatever will take the source code from that dependency from node_modules and process it on the spot, much like compiling. The end result is a single dist.js/bundle.js/package.js/vendor.js whatever, that you include in your HTML. Now you don't have to edit your HTML ever again for dependencies.
> I now prefer webpack over browserify, as it is a more universal approach to processing source files and once you have a basic setup working, adding more things to it is very easy (using so called 'loaders', for CSS, TypeScript, inlining sources, LESS, minifying, JSHinting etc. etc.).
> 
> In fact, I ditched my entire gulp build script in favor of a streamlined webpack config!
