### ISSUE TITLE
Ability to query log level

### ISSUE THREAD

**Issue by mikesir87** [better-js-logging/angular-logger#23]
As some of my log statements may be costly in production (like stringify-ing objects), it would be nice to query if logging is enabled at a certain level.  For example...

```javascript
var logger = $log.getInstance('SampleService');
if (logger.isDebugEnabled()) {
  // Generate debug message
  logger.debug( myDebugMessage );
}
```

I took a look at the source (although very quickly) and would be happy to provide a PR.  Any recommendations on the cleanest way to fit something like this in?

**Comment by bbottema** [comment]
Actually, this check is performed internally already before doing any of the costly operations.

See https://github.com/better-js-logging/better-logging-base/blob/master/src/logging-enhancer.js#L19

**Comment by mikesir87** [comment]
Sure, but by that time, I've already constructed my message, which could have been costly.  Looking to see if I can prevent even needing to construct the message if possible.

**Comment by bbottema** [comment]
In that case you should work with place holders, so your message is not yet created. Did you know you can even pass in functions that are only invoked if the above threshold check returns true?

```
logger.info("This has a placeholder with [%s]", function() { return "function output"; });
```

[jsfiddle](https://jsfiddle.net/plantface/8rnznkkb/)

**Comment by mikesir87** [comment]
Ok. I was not aware of that capability, which looks like it should do the trick.  Thanks!

**Comment by bbottema** [comment]
I amended the documentation and examples with an example of this feature, because it's pretty cool!

**Comment by mikesir87** [comment]
Fantastic! Thanks for the quick responses and the help!
