### ISSUE TITLE
write log level in logged message

### ISSUE THREAD

**Issue by bbottema** [better-js-logging/angular-logger#8]
Moved from https://github.com/pdorgambide/angular-logger/issues/23

> I would like to be able to see in logged messages which ones are ERROR or just WARN.
> 
> We could make prefixPattern to accept a third parameter corresponding to the log level used to log the message.

**Comment by bbottema** [comment]
@pdesoyres, you mean to say you would like to add the _text_ " DEBUG" or "ERROR" to the message prefix? Or do you want to see only a certain level of messages in the log excluding all other (above or below).

**Comment by pdesoyres** [comment]
@bbottema, yes I would like to see the log level ("DEBUG" for example) in the message prefix. This is because, when I read the output log, I want to see very easily the log level of the message.

**Comment by bbottema** [comment]
@pdesoyres, what pattern would you like as a default? Currently it is `'%s::[%s]> '` (timestamp, then context).

**Comment by pdesoyres** [comment]
@bbottema Something like `'%s::[%s] [%s]> '` (timestamp; logLevel, context) may fit my need.

**Comment by bbottema** [comment]
Alright, should be solved in [v1.1.0](https://github.com/better-js-logging/angular-logger/releases/tag/1.1.0).

By default, the loglevel is not shown, unless sprintf.js is missing in which case angular-logger falls back to basic prefixpattern that includes the logging level.

To add logging level to the prefix pattern, simply add the third placeholder:

```
logEnhancerProvider.prefixPattern = '%s::[%s] [%s]> ';
```
- [plunkr](http://plnkr.co/edit/6dR0hMPNfydTk1s6ccJV?p=preview)

**Comment by pdesoyres** [comment]
@bbottema thank you for the fast implementation ! It works perfectly.
