### ISSUE TITLE
using $log.[logmethod]() does not respect log levels

### ISSUE THREAD

**Issue by edamon** [better-js-logging/angular-logger#9]
I would expect that if I set the logLevel to {'*', logEnhancerProvider.LEVEL.INFO}, when I call $log.debug('should not see this in the console'), that it would respect the log level.  It is not.

http://plnkr.co/edit/gZw4HdSgtRj6dgahkgQy?p=preview

only the objects from GetInstance() respect the log levels.

**Comment by bbottema** [comment]
I will take a look somewhere this week.

**Comment by bbottema** [comment]
Should be fixed in v1.0.4.
